# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "bookmarks", :force => true do |t|
    t.column "box_id",     :integer,                                  :null => false
    t.column "url",        :string,   :limit => 1024, :default => "", :null => false
    t.column "name",       :string,                   :default => "", :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "visited_at", :datetime
    t.column "position",   :integer,                  :default => 0,  :null => false
  end

  add_index "bookmarks", ["id"], :name => "indx_bookmarks_id"
  add_index "bookmarks", ["box_id"], :name => "fki_bookmarks_box_id"

  create_table "boxes", :force => true do |t|
    t.column "column_id", :integer,                                           :null => false
    t.column "title",     :string,  :limit => 64, :default => "Rename Me...", :null => false
    t.column "style",     :string,  :limit => 16
    t.column "collapsed", :boolean,               :default => false,          :null => false
    t.column "position",  :integer,                                           :null => false
  end

  add_index "boxes", ["id"], :name => "indx_boxes_id"
  add_index "boxes", ["column_id"], :name => "fki_boxes_column_id"

  create_table "columns", :force => true do |t|
    t.column "user_id",  :integer, :null => false
    t.column "position", :integer, :null => false
  end

  add_index "columns", ["id"], :name => "indx_columns_id"
  add_index "columns", ["user_id"], :name => "fki_columns_user_id"

  create_table "inboxes", :force => true do |t|
    t.column "user_id", :integer, :null => false
  end

  add_index "inboxes", ["id"], :name => "indx_inboxes_id"
  add_index "inboxes", ["user_id"], :name => "fki_inboxes_user_id"

  create_table "inboxmarks", :force => true do |t|
    t.column "inbox_id",   :integer,                                  :null => false
    t.column "url",        :string,   :limit => 1024, :default => "", :null => false
    t.column "name",       :string,                   :default => "", :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "visited_at", :datetime
    t.column "position",   :integer,                                  :null => false
  end

  add_index "inboxmarks", ["id"], :name => "indx_inboxmarks_id"
  add_index "inboxmarks", ["inbox_id"], :name => "fki_inboxmarks_inbox_id"

  create_table "sessions", :force => true do |t|
    t.column "sessid",     :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["sessid"], :name => "indx_sessions_sessid"

  create_table "support_requests", :force => true do |t|
    t.column "option",      :string,                 :default => "",    :null => false
    t.column "description", :string,  :limit => 510, :default => "",    :null => false
    t.column "from_user",   :boolean,                :default => false, :null => false
    t.column "user_id",     :integer
    t.column "email",       :string,                 :default => "",    :null => false
  end

  create_table "trashboxes", :force => true do |t|
    t.column "user_id", :integer, :null => false
  end

  add_index "trashboxes", ["id"], :name => "indx_trashboxes_id"
  add_index "trashboxes", ["user_id"], :name => "fki_trashboxes_user_id"

  create_table "trashboxmarks", :force => true do |t|
    t.column "trashbox_id", :integer,                                  :null => false
    t.column "url",         :string,   :limit => 1024, :default => "", :null => false
    t.column "name",        :string,                   :default => "", :null => false
    t.column "created_at",  :datetime,                                 :null => false
    t.column "visited_at",  :datetime
    t.column "position",    :integer,                                  :null => false
  end

  add_index "trashboxmarks", ["id"], :name => "indx_trashmarks_id"
  add_index "trashboxmarks", ["trashbox_id"], :name => "fki_trashmarks_trashbox_id"

  create_table "users", :force => true do |t|
    t.column "salted_password", :string,   :limit => 40, :default => "",    :null => false
    t.column "email",           :string,   :limit => 60, :default => "",    :null => false
    t.column "salt",            :string,   :limit => 40, :default => "",    :null => false
    t.column "verified",        :boolean,                :default => false
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :boolean,                :default => false
    t.column "delete_after",    :datetime
    t.column "uuid",            :string,   :limit => 32, :default => "",    :null => false
  end

  add_index "users", ["uuid"], :name => "indx_users_uuid", :unique => true
  add_index "users", ["email"], :name => "indx_users_email", :unique => true
  add_index "users", ["id"], :name => "indx_users_id"
  add_index "users", ["email", "salted_password"], :name => "indx_users_email_salted_password"

end
